<%@ Page Language="C#" MasterPageFile="~/Admin/Admin.master" AutoEventWireup="true"
 CodeFile="Question_Master.aspx.cs" Inherits="Admin_Question_Master" Title="问题管理"  Theme="MemberShipSkin"%>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
	<asp:ObjectDataSource ID="OQuestion" runat="server" OldValuesParameterFormatString="original_{0}" SelectMethod="GetData" TypeName="GetQuestionByGroupTableAdapters.SelectAllQuestionbyGroupTableAdapter">
		<SelectParameters>
			<asp:ControlParameter ControlID="DropDownList1" DefaultValue="0" Name="groupid" PropertyName="SelectedValue"
				Type="Int64" />
		</SelectParameters>
	</asp:ObjectDataSource>
	<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
		DeleteCommand="QuestionDelete" DeleteCommandType="StoredProcedure" SelectCommand="SelectAllQuestionbyGroup"
		SelectCommandType="StoredProcedure">
		<DeleteParameters>
			<asp:Parameter Name="id" Type="Int64" />
		</DeleteParameters>
		<SelectParameters>
			<asp:ControlParameter ControlID="DropDownList1" DefaultValue="" Name="groupid" PropertyName="SelectedValue"
				Type="Int64" />
		</SelectParameters>
	</asp:SqlDataSource>
	<asp:ObjectDataSource ID="OGroup" runat="server" OldValuesParameterFormatString="original_{0}" SelectMethod="GetData" TypeName="GetGroupTableAdapters.GroupSelectTableAdapter"></asp:ObjectDataSource>
	<asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="OGroup" DataTextField="name"
		DataValueField="id" AutoPostBack="True">
	</asp:DropDownList>
	<asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True"
		AutoGenerateColumns="False" DataKeyNames="id" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True">
		<Columns>
				<asp:TemplateField>
				<HeaderTemplate>Edit</HeaderTemplate>
				<ItemTemplate>
				<a href="Question_Add.aspx?id=<%#DataBinder.Eval(Container.DataItem, "id") %>&">编辑</a>
				</ItemTemplate>
				</asp:TemplateField>
			<asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True"
				SortExpression="id" />

				<asp:TemplateField>
				<HeaderTemplate>Title</HeaderTemplate>
				<ItemTemplate>
				<a href="Answer_Master.aspx?id=<%#DataBinder.Eval(Container.DataItem, "id") %>&"><%#DataBinder.Eval(Container.DataItem, "title")%></a>
				</ItemTemplate>
				</asp:TemplateField>
			<asp:BoundField DataField="AcceptedCount" HeaderText="Accepted" SortExpression="AcceptedCount" />
			<asp:BoundField DataField="SubmitCount" HeaderText="Submit" SortExpression="SubmitCount" />
			<asp:BoundField DataField="Ratio" DataFormatString="{0}%" HeaderText="Ratio" ReadOnly="True"
				SortExpression="Rotio" />
		</Columns>
	</asp:GridView>
</asp:Content>

