// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ssds", Scope = "type", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions.#Delete(Microsoft.Samples.Cloud.Data.SsdsContainer,System.Collections.Generic.IEnumerable`1<System.String>,System.Func`3<System.String,System.Exception,System.Boolean>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions.#DeleteAsync(Microsoft.Samples.Cloud.Data.SsdsContainer,System.Collections.Generic.IEnumerable`1<System.String>,System.Action`1<System.Collections.Generic.IEnumerable`1<System.String>>,System.Func`3<System.String,System.Exception,System.Boolean>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions.#Insert(Microsoft.Samples.Cloud.Data.SsdsContainer,System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsBlobEntity>,System.Func`3<Microsoft.Samples.Cloud.Data.SsdsBlobEntity,System.Exception,System.Boolean>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions.#Insert`1(Microsoft.Samples.Cloud.Data.SsdsContainer,System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsEntity`1<!!0>>,System.Func`3<Microsoft.Samples.Cloud.Data.SsdsEntity`1<!!0>,System.Exception,System.Boolean>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions.#UpdateAsync`1(Microsoft.Samples.Cloud.Data.SsdsContainer,System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsEntity`1<!!0>>,System.Action`1<System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsEntity`1<!!0>>>,System.Func`3<Microsoft.Samples.Cloud.Data.SsdsEntity`1<!!0>,System.Exception,System.Boolean>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions.#UpdateAsync(Microsoft.Samples.Cloud.Data.SsdsContainer,System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsBlobEntity>,System.Action`1<System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsBlobEntity>>,System.Func`3<Microsoft.Samples.Cloud.Data.SsdsBlobEntity,System.Exception,System.Boolean>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions.#Update`1(Microsoft.Samples.Cloud.Data.SsdsContainer,System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsEntity`1<!!0>>,System.Func`3<Microsoft.Samples.Cloud.Data.SsdsEntity`1<!!0>,System.Exception,System.Boolean>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions.#InsertAsync`1(Microsoft.Samples.Cloud.Data.SsdsContainer,System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsEntity`1<!!0>>,System.Action`1<System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsEntity`1<!!0>>>,System.Func`3<Microsoft.Samples.Cloud.Data.SsdsEntity`1<!!0>,System.Exception,System.Boolean>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions.#Update(Microsoft.Samples.Cloud.Data.SsdsContainer,System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsBlobEntity>,System.Func`3<Microsoft.Samples.Cloud.Data.SsdsBlobEntity,System.Exception,System.Boolean>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Cloud.Storage.PExtensions.SsdsContainerParallelismExtensions.#InsertAsync(Microsoft.Samples.Cloud.Data.SsdsContainer,System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsBlobEntity>,System.Action`1<System.Collections.Generic.IEnumerable`1<Microsoft.Samples.Cloud.Data.SsdsBlobEntity>>,System.Func`3<Microsoft.Samples.Cloud.Data.SsdsBlobEntity,System.Exception,System.Boolean>)")]
